### ISSUE TITLE
Production Use

### ISSUE THREAD

**Issue by zip-chanko** [Dynatrace/dynatrace-otel-collector#147]
**Is your feature request related to a problem? Please describe.**
This is a good solution which overcome [the limitation of multiple exportors from the builtin prometheus monitoring](https://docs.dynatrace.com/docs/shortlink/monitor-prometheus-metrics#multiple-exporters-in-a-pod). 

**Describe the solution you'd like**
For the production environment which has around ~2500 pods on Amazon EKS. May I know if the pre-release version is stable in production and there isn't any breaking changes in near future?

**Comment by arminru** [comment]
Hi @zip-chanko!
We don't expect any breaking changes but also can't guarantee there will be none. You can find each component's stability defined in the upstream repositories with the levels specified at https://github.com/open-telemetry/opentelemetry-collector#stability-levels.
We plan to remove the production-use disclaimer and pre-release tag in the next few weeks and will provide full support from there on.

**Comment by arminru** [comment]
Hey @zip-chanko!
We went ahead as mentioned above and removed the prod use disclaimer and pre-release tag last week and put the distro under full support as described in the README.
