### ISSUE TITLE
metricstransformer processor to the collector

### ISSUE THREAD

**Issue by pahiz** [Dynatrace/dynatrace-otel-collector#284]
**Is your feature request related to a problem? Please describe.**
We are currently using different collector to export OTel metrics to Dynatrace, why we are doing this is because of the 

**Describe the solution you'd like**
Include the metricstransformer processor from OTel contrib. library. Or if you have already processor for changing the name of the metric on fly with some different processor.

**Describe alternatives you've considered**
Running different collector than Dynatrace one to have the metricstransformer processor available.

**Additional context**

the processor logic to be replaced

metricstransform:
    transforms:
      include: ^(stitching\.process|templare\.runtime)
      match_type: regexp
      action: update
      new_name: `${ENV_NAME}.$${1}`

**Comment by odubajDT** [comment]
Hello! 

The `transform` processor (which is part of the Dynatrace-collector) should be capable of renaming the name of the metric. `transform` processor works a little bit different than `metricstransform` processor as it uses a list of statements, which mostly are part of the OTTL functions.

The documentation and examples of `transform` processor usage can be found [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor) and I would recommend using the OTTL [editors](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#editors) for renaming the metric.

If there are any other questions do not hesitate to reach out!

**Comment by pahiz** [comment]
Thank you, I will return to this in upcoming weeks when implementing the Dynatrace Collector in use.

**Comment by pahiz** [comment]
I can confirm that transform processor is able to do exactly same things as metricstransformer.

Closing as there is no need for metricstransformer in this scope.
