### ISSUE TITLE
Systemd service file has Documentation key in wrong section

### ISSUE THREAD

**Issue by weavage** [Dynatrace/dynatrace-otel-collector#334]
**Describe the bug**
The systemd service file has the Documentation key in the wrong section. The Documentation key is currently in the Service section, but should be moved to the Unit section. See systemd documentation [here](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#%5BUnit%5D%20Section%20Options). Current line causing issues [here](https://github.com/Dynatrace/dynatrace-otel-collector/blob/f7d42dc38118452f66701193f06c551f13c4b34d/internal/release/dynatrace-otel-collector.service#L13). 

Example warning generated in logs:
```
systemd[1]: /usr/lib/systemd/system/dynatrace-otel-collector.service:13: Unknown key name 'Documentation' in section 'Service', ignoring.
```

**To Reproduce**
1. Install Dynatrace OTel Collector
2. Start/restart the service via systemd
3. error is shown in /var/log/messages or via journalctl

**Expected behavior**
Service shouldn't generate warning

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: AlmaLinux 9.4
 - Systemd: 252-32.el9_4.6

**Additional context**

**Comment by mowies** [comment]
thanks for posting this! i'll fix it
